# Use Numpy to support calculation

In [1]:
import numpy as np

## 1. Array
#### 1.1Created by list

In [5]:
# Create vector array by list
my_list1 = [1,2,3,4]
my_arr1 = np.array(my_list1)
print my_arr1

[1 2 3 4]


In [10]:
# Create matrix arry by list in list
my_list2 = [[1, 2, 3, 4],
            [7, 8, 9, 10]]
my_arr2 = np.array(my_list2)
print my_arr2

[[ 1  2  3  4]
 [ 7  8  9 10]]


#### 1.2 Create by numpy: zeros, ones, eye, arange

In [24]:
# Create all zeros, ones, and identity matrix
print 'np.zeros(5)', "\n", np.zeros(5), "\n" # Zeros vector
print 'np.zeros([3, 6])', "\n", np.zeros([3, 6]), "\n" # Zeros matrix
print "np.ones([2, 2])", "\n", np.ones([2, 2]), "\n" # Ones matrix
print 'np.eye(5)', '\n', np.eye(5) # Identity matrix

np.zeros(5) 
[ 0.  0.  0.  0.  0.] 

np.zeros([3, 6]) 
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]] 

np.ones([2, 2]) 
[[ 1.  1.]
 [ 1.  1.]] 

np.eye(5) 
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [25]:
# Other than that, we can also create number arrays using arrange (analogy of range)
print "np.arange(9)", np.arange(9)

np.arange(55) [0 1 2 3 4 5 6 7 8]


#### 1.3 Indexing

In [26]:
# Before indexing, we need to know the shape of the array
my_arr2.shape

(2, 4)

In [33]:
# Using [] to make index
# If no second item, take row by default
print 'All first row:', my_arr2[0]
print 'First item in second row:', my_arr2[1, 0], my_arr2[1][0] # Both works

All first row: [1 2 3 4]
First item in second row: 7 7


In [60]:
# Fancy Indexing
print my_arr2[[0,1]]
print my_arr2[:, [1,2]]

[[999   2   3   4]
 [  7   8   9  10]]
[[2 3]
 [8 9]]


#### 1.4 Operation with scalar

In [39]:
# +, -, *, /, **
print 'my_arr2*2:', "\n", my_arr2*2, "\n"
print 'my_arr2+2:', "\n", my_arr2+2, "\n"
print 'my_arr2/2:', "\n", my_arr2/2, "\n"
print 'my_arr2-2:', "\n", my_arr2-2, "\n"
print 'my_arr2**2', "\n", my_arr2**2, "\n"
# All operation with scalar are independent with each items

my_arr2*2: 
[[ 2  4  6  8]
 [14 16 18 20]] 

my_arr2+2: 
[[ 3  4  5  6]
 [ 9 10 11 12]] 

my_arr2/2: 
[[0 1 1 2]
 [3 4 4 5]] 

my_arr2-2: 
[[-1  0  1  2]
 [ 5  6  7  8]] 

my_arr2**2 
[[  1   4   9  16]
 [ 49  64  81 100]] 



#### 1.5 ***Slice and Copy

In [41]:
# ***Important*** Slice is a projection from the original. Thus if slice change, the origin changes
my_arr3 = my_arr2 [:, 0:3]
print my_arr3

[[1 2 3]
 [7 8 9]]


In [42]:
# If my_arr3 changes, the origin my_arr2 also changes
my_arr3[0,0] = 999
print my_arr3
print my_arr2

[[999   2   3]
 [  7   8   9]]
[[999   2   3   4]
 [  7   8   9  10]]


In [51]:
# To really make a copy
my_arr2_copy = my_arr2.copy() # Remember the ()
my_arr2_copy[0,0] = -10
print "my_arr2_copy", '\n', my_arr2_copy, "\n"
print "my_arr2", "\n", my_arr2

my_arr2_copy 
[[-10   2   3   4]
 [  7   8   9  10]] 

my_arr2 
[[999   2   3   4]
 [  7   8   9  10]]
